### ISSUE TITLE
Invalid syntax at position 0: unrecognized node type: 718

### ISSUE THREAD

**Issue by Keats** [sfackler/rust-postgres-macros#14]
I'm getting the above error with a varying node type number on all the queries i'm trying it on (for example the ones on https://github.com/Keats/webrust/blob/master/src/db.rs#L32-L35)

```rust
conn.execute(sql!("DROP TABLE IF EXISTS passwords;"), &[]).unwrap();
```

Did I miss something?

**Comment by sfackler** [comment]
Looks like the issue is that `raw_expression_tree_walker`, which we use to count query parameters, doesn't support some query types: https://github.com/postgres/postgres/blob/master/src/backend/nodes/nodeFuncs.c#L2984-L2998. Might have to make the query counting logic a bit more robust to deal with it.
